defaults:
  - arch: resnet34
  - env: local
  - datamodule: cifar10
  - optimizer: sgd
  - scheduler: plateau

epochs: 90
batch_size: 128

hydra:
  run:
    dir: ${env.savedir}/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}